"""delete avatar url form user

Revision ID: e2eabad95f54
Revises: 3d2935c48b9c
Create Date: 2026-03-06 09:20:35.078005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2eabad95f54"
down_revision: str | None = "3d2935c48b9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
